# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selen', '0002_remove_tripadvisorhotelcity_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripadvisorhotel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
